### PR TITLE
ok gcat I added lang files can you merge now

### PR DESCRIPTION
**Pull request by TheFieryFalcon**
not now wait a sec I gotta fix a typo

### CODE REVIEW

**Review by Gcat101 — CHANGES_REQUESTED** [review]
Abbr must be qp

**Review by Gcat101 — COMMENTED** [review]
Did you try the description? Does it fit into the popup size?
Also it lacks \<b\> tags, which will probably make it quite boring

**Review by Gcat101 — COMMENTED** [review]
We use json5 :trollface:

**Comment by tizu69** [comment]
cool preview build url leak pepecatandlaugh

**Comment by tizu69** [comment]
not sure if this is feasible specifically for this pr, but wouldn't it be better if the description of modpacks were md instead of html?

**Review by Gcat101 — CHANGES_REQUESTED** [review]
Don't change internal code, idiot

**Review by Gcat101 — CHANGES_REQUESTED** [review]
Also if you are going to change the styles, use tailwind ffs

**Review by Gcat101 — CHANGES_REQUESTED** [review]
image

this is a really crusty image, please replace

**Review by Gcat101 — COMMENTED** [review]
image

nope

**Review by Gcat101 — COMMENTED** [review]
image

ok this one works

**Review by Gcat101 — CHANGES_REQUESTED** [review]
good to go

**Review by Gcat101 — APPROVED** [review]
good to go

**Pull request merged**
